### ISSUE TITLE
SwearWord module generates yara syntax errors

### ISSUE THREAD

**Issue by sudocurse** [mandiant/thiri-notebook#3]
Using the SwearWord engine with any term+encoder+filetype generates the following:
```
rule M_Methodology_SwearWord_pe_think_plain {
    meta:
        author="auto-generated"
        description="Auto-generated rule for: think, thinker, thinking, thinks"
        created="2022-04-22"
        md5=""
        sid="1"
        rev="1" 
    strings:
		$filetype= | 50 45 00 00|
		$search_think = /[^A-Za-z]{1}(think|thinker|thinking|thinks)[^A-Za-z]{1}/ ascii nocase wide
		
	condition:
		$filetype at 0x3c and $search_think and not 
}
```

Lines 10 and 14 have syntax errors. Things that might be going on:
* I think the filetype is supposed to be surrounded by `{`/`}` 
* The dangling "and not" at the end of the condition
* I don't really know yara that well

**Comment by ramen0x3f** [comment]
Ah good catch! The class/object type I use has different conditions for Snort (pipes) and Yara (curly braces), and I must have mixed them up in that engine. I'll push an update for this shortly, thank you!
